name: Deploy to YoungcoderFTP  
on:  
  push:  
    branches: [ main ]  
  pull_request:  
    types: [closed]  
    branches: [ main ]  

jobs:  
  deploy:  
    # Только для твоих пушей или мерженых PR  
    if: |  
      (github.event_name == 'push' && github.actor == 'KaDeaT') ||  
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v4  

      - name: Upload ./lang_c/ files via FTP  
        uses: SamKirkland/FTP-Deploy-Action@4.3.0  # Готовый Action для FTP  
        with:  
          server: ${{ secrets.FTP_SERVER }}  
          username: ${{ secrets.FTP_USERNAME }}  
          password: ${{ secrets.FTP_PASSWORD }}  
          local-dir: ./lang_c/  
          server-dir: /lang_c/  
          dangerous-clean-slate: false
          git-ftp: true

      - name: Upload ./ide/ files via FTP  
        uses: SamKirkland/FTP-Deploy-Action@4.3.0  
        with:  
          server: ${{ secrets.FTP_SERVER }}  
          username: ${{ secrets.FTP_USERNAME }}  
          password: ${{ secrets.FTP_PASSWORD }}  
          local-dir: ./ide/  
          server-dir: /ide/  
          dangerous-clean-slate: false
          git-ftp: true